Controllers films users
k-mesavage/java-filmorate pull request #21
Opened 2023-06-02 12:32 UTC by k-mesavage

2023-06-03 00:10 UTC, AnastasiyaFomkina requested changes
Привет! Молодец, что выполнил дополнительное задание со спринговой валидацией 👍

2023-06-03 00:10 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isAfter(MIN_RELEASE_DATE)) {
_Опционально_
Можно создать [свою кастомную аннотацию валидации](https://reflectoring.io/bean-validation-with-spring-boot/#a-custom-validator-with-spring-boot:~:text=to%20none.-,A%20Custom%20Validator%20with%20Spring%20Boot,-If%20the%20available), чтобы не писать однотипные проверки

2023-06-03 00:10 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@Slf4j
Нужно добавить логирование для операций, которые изменяют сущности — добавляют и обновляют их. И нужно логировать причины ошибок — например, если валидация не пройдена.

2023-06-03 00:10 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Pattern(regexp = "\\S*")
Клево, что используешь `@Pattern` для проверки на пробелы 👍

2023-06-03 00:11 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +import org.springframework.web.bind.annotation.*;
_Саморазвитие_
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/using-wildcard-imports-in-java/) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2023-06-04 22:16 UTC, AnastasiyaFomkina requested changes

2023-06-04 22:16 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public ArrayList<User> getAllUsers() {
Нужно возвращать интерфейс, а не конкретную реализацию

2023-06-04 22:16 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        Film film = Film.builder()
Нужно вынести повторяющийся код в отдельный метод или создавать каждый раз перед тестом в `@BeforeEach`

2023-06-04 22:16 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        HttpClient client = HttpClient.newHttpClient();
 Лучше вынести в [@BeforeEach](https://habr.com/ru/articles/590741/)

2023-06-05 08:42 UTC, k-mesavage commented on src/main/java/ru/yandex/practicum/filmorate/manager/Manager.java
> +    ArrayList<User> getAllUsers() {
Ааааааа... Понял!

2023-06-05 16:49 UTC, AnastasiyaFomkina approved these changes

2023-06-06 18:13 UTC, merged